import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
    in property <string> results: "";
    callback divide-income(string);

    default-font-family: "Amazon Ember Display";
    title: "Income Calculator";

    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income:";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 600;
            }
        }

        Row {
            income := LineEdit {
                horizontal-alignment: center;
                font-size: 14px;
                placeholder-text: "Enter your number";
                height: 30px;
            }
        }

        Row {
            Button {
                text: "Calculate";
                primary: true;
                height: 30px;
                clicked => {
                    divide-income(income.text);
                }
            }
        }

        Row {
            VerticalBox {
                Rectangle {
                    height: 60px;
                    Text {
                        text: root.results;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        font-size: 16px;
                        font-weight: 500;
                        color: #d2d2d6;
                    }
                }
            }
        }
    }
}
