import { Button, VerticalBox, LineEdit } from "std-widgets.slint";

export component AppWindow inherits Window {
default-font-family: "Amazon Ember Display";
    GridLayout {
        padding: 50px;
        spacing: 25px;
        Row {
            Text {
                text: "Enter Total Income:";
                horizontal-alignment: center;
                font-size: 24px;
                font-weight: 600;
            }
        }

        Row {
            LineEdit {
                font-size: 14px;
                placeholder-text: "Enter your number";
            }
        }

        Row {
            Button {
                text: "Calculate";
            }
        }
    }
}
